[package]
name = "garage_util"
version = "0.8.4"
authors = ["Alex Auvolat <alex@adnab.me>"]
edition = "2018"
license = "AGPL-3.0"
description = "Utility crate for the Garage object store"
repository = "https://git.deuxfleurs.fr/Deuxfleurs/garage"
readme = "../../README.md"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garage_db.workspace = true

arc-swap = "1.0"
async-trait = "0.1"
blake2 = "0.10"
bytes = "1.0"
bytesize = "1.2"
digest = "0.10"
err-derive = "0.3"
hexdump = "0.1"
xxhash-rust = { version = "0.8", default-features = false, features = ["xxh3"] }
hex = "0.4"
lazy_static = "1.4"
tracing = "0.1"
rand = "0.8"
sha2 = "0.10"

chrono = "0.4"
rmp-serde = "1.1.2"
serde = { version = "1.0", default-features = false, features = ["derive", "rc"] }
serde_json = "1.0"
toml = "0.6"

futures = "0.3"
tokio = { version = "1.0", default-features = false, features = ["rt", "rt-multi-thread", "io-util", "net", "time", "macros", "sync", "signal", "fs"] }

netapp = "0.10"

http = "0.2"
hyper = "0.14"

opentelemetry = { version = "0.17", features = [ "rt-tokio", "metrics", "trace" ] }

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
mktemp = "0.5"

[features]
k2v = []
